- hosts: centos
  tasks:
    - name: Install EPEL 
      yum:
        name: epel-release.noarch
        state: present
        update_cache: True
        
        
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        
        
    - name: Install default packages
      yum: 
       name: '{{ item }}' 
       state: present
       update_cache: True
      with_items:
        - atop 
        - nload 
        - iftop
        - wget
        - smartmontools
        - strace 
        - mc
        - vim
        - nano
        - tmux
        - logwatch
        - iotop
        - mytop
        - net-tools


    - name: Start smartd
      systemd: 
       name: smartd 
       state: started
              
    - name: Enable smartd
      systemd: 
       name: smartd 
       enabled: yes
    
    - name: Change loginterval atop
      lineinfile: dest=/etc/sysconfig/atop regexp='^LOGINTERVAL' line='LOGINTERVAL=30'
    
      
    - name: Enable atop
      systemd:
       name: atop
       enabled: yes
       
    - name: Restart atop
      service:
         name: atop
         state: restarted
       
    - name: Copy logrotate script
      copy: 
       src: ./atop
       dest: /etc/logrotate.d/
       

    - name: add smart disks
      lineinfile: dest=/etc/smartmontools/smartd.conf
                  backrefs=yes
                  regexp='^DEVICESCAN -H -m'
                  insertafter='DEVICESCAN -H -m'
                  line='/dev/sda -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
                  state=present
      tags: ssd1
      
    - name: add 2 smart disks
      lineinfile: 
          dest: /etc/smartmontools/smartd.conf      
          line: '{{ item }}'
      with_items:
          - '/dev/sda -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdb -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'

      tags: ssd2
      
    - name: add 3 smart disks
      lineinfile: 
          dest: /etc/smartmontools/smartd.conf      
          line: '{{ item }}'
      with_items:
          - '/dev/sda -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdb -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdc -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'

      tags: ssd3



    - name: Delete default smart line
      lineinfile: dest=/etc/smartmontools/smartd.conf
                  regexp='^DEVICESCAN -H -m'
                  state=absent
      
    - name: Check mdadm exist
      stat:
       path: /etc/mdadm.conf
      register: stat_result

    - name: Change mdadm conf
      lineinfile: dest=/etc/mdadm.conf backrefs=yes regexp='^MAILADDR' line='MAILADDR reports112@freehost.com.ua'
      when: stat_result.stat.exists

    - name: '/etc/fstab: Set options for mount point "/" '
      lineinfile:
         path: /etc/fstab
         backup: yes
         backrefs: yes
         regexp: '^(\S+\s+/\s+\S+\s+)(?!(?:\S*,)?discard(?:,\S*)?\s+)(\S+)(\s+.+)$'
         line: '\1noatime,nodiratime,commit=120,discard,\2\3'
      tags: ssd
- hosts: debian
  tasks:
        
    - name: Install default packages
      apt: 
       name: '{{ item }}' 
       state: present
       update_cache: True
      with_items:
        - atop 
        - nload 
        - iftop
        - wget
        - smartmontools
        - mc
        - vim
        - nano
        - tmux
        - man-db
        - logwatch
        - iotop
        - curl


    - name: Start smartd
      systemd: 
       name: smartd 
       state: started
       
       
    - name: Enable smartd
      systemd: 
       name: smartd 
       enabled: yes
    
    - name: Setting fsck in grub
      lineinfile: dest=/etc/default/grub backrefs=yes regexp='^GRUB_CMDLINE_LINUX_DEFAULT' line='GRUB_CMDLINE_LINUX_DEFAULT="nomodeset fsck.repair=yes"'
      
    - name: update grub
      shell: update-grub
      
    - name: Change loginterval atop
      lineinfile: dest=/usr/share/atop/atop.daily backrefs=yes regexp='^LOGINTERVAL' line='LOGINTERVAL=30'
    
    - name: Enable atop
      systemd:
       name: atop
       enabled: yes
      tags:
      - atop1
    - name: Restart atop
      service:
         name: atop
         state: restarted
       
    - name: Copy logrotate script
      copy: 
       src: ./atop
       dest: /etc/logrotate.d/
       
    - name: add smart disks
      lineinfile: dest=/etc/smartd.conf
                  backrefs=yes
                  regexp='^DEVICESCAN -d'
                  insertafter='DEVICESCAN -d'
                  line='/dev/sda -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
                  state=present
      tags: ssd1
      
    - name: add 2 smart disks
      lineinfile: 
          dest: /etc/smartd.conf      
          line: '{{ item }}'
      with_items:
          - '/dev/sda -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdb -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'

      tags: ssd2
      
    - name: add 3 smart disks
      lineinfile: 
          dest: /etc/smartd.conf      
          line: '{{ item }}'
      with_items:
          - '/dev/sda -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdb -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdc -a -s (S/../../(1|3|6)/01|L) -m reports112@freehost.com.ua -M diminishing'

      tags: ssd3

    - name: Delete default smart line
      lineinfile: dest=/etc/smartd.conf
                  regexp='^DEVICESCAN -d'
                  state=absent

      
    - name: Restart smart
      service:
         name: smartd
         state: restarted
               
    - name: Check mdadm exist
      stat:
       path: /etc/mdadm/mdadm.conf
      register: stat_result

    - name: Change mdadm conf
      lineinfile: dest=/etc/mdadm/mdadm.conf backrefs=yes regexp='^MAILADDR' line='MAILADDR reports112@freehost.com.ua'
      when: stat_result.stat.exists
      
    - name: '/etc/fstab: Set options for mount point root '
      lineinfile:
       path: /etc/fstab
       backup: yes
       backrefs: yes
       regexp: '^(\S+\s+/\s+\S+\s+)(?!(?:\S*,)?discard(?:,\S*)?\s+)(\S+)(\s+.+)$'
       line: '\1discard,noatime,commit=120,\2\3'
      tags: ssd
      
- hosts: ubuntu
  tasks:
        
    - name: Install default packages
      apt: 
       name: '{{ item }}' 
       state: present
       update_cache: True
      with_items:
        - atop 
        - nload 
        - iftop
        - wget
        - smartmontools
        - strace 
        - mc
        - vim
        - nano
        - tmux
        - mlocate
        - man-db
        - logwatch
        - iotop
        - mytop
        - gnupg

    - name: Start smartd
      systemd: 
       name: smartd 
       state: started
       
       
    - name: Enable smartd
      systemd: 
       name: smartd 
       enabled: yes
    
    - name: Setting fsck in grub
      lineinfile: dest=/etc/default/grub backrefs=yes regexp='^GRUB_CMDLINE_LINUX_DEFAULT' line='GRUB_CMDLINE_LINUX_DEFAULT="nomodeset fsck.repair=yes"'
      
    - name: update grub
      shell: update-grub
      
    - name: Change loginterval atop
      lineinfile: dest=/usr/share/atop/atop.daily backrefs=yes regexp='^LOGINTERVAL' line='LOGINTERVAL=30'
    
    - name: Enable atop
      systemd:
       name: atop
       enabled: yes
      tags:
      - atop1
    - name: Restart atop
      service:
         name: atop
         state: restarted
       
    - name: Copy logrotate script
      copy: 
       src: ./atop
       dest: /etc/logrotate.d/
       
    - name: Enable vm.swappiness=1
      lineinfile: dest=/etc/sysctl.conf regexp='' insertafter=EOF line='vm.swappiness=1'
      tags: ssd      
      
       
    - name: add smart disks
      lineinfile: dest=/etc/smartd.conf
                  backrefs=yes
                  regexp='^DEVICESCAN -d'
                  insertafter='DEVICESCAN -d'
                  line='/dev/sda -a -s (S/../../(2|4)/01|L/../../6/01) -m reports112@freehost.com.ua -M diminishing'
                  state=present
      tags: ssd1
      
    - name: add 2 smart disks
      lineinfile: 
          dest: /etc/smartd.conf      
          line: '{{ item }}'
      with_items:
          - '/dev/sda -a -s (S/../../(2|4)/01|L/../../6/01) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdb -a -s (S/../../(2|4)/01|L/../../6/01) -m reports112@freehost.com.ua -M diminishing'

      tags: ssd2
      
    - name: add 3 smart disks
      lineinfile: 
          dest: /etc/smartd.conf      
          line: '{{ item }}'
      with_items:
          - '/dev/sda -a -s (S/../../(2|4)/01|L/../../6/01) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdb -a -s (S/../../(2|4)/01|L/../../6/01) -m reports112@freehost.com.ua -M diminishing'
          - '/dev/sdc -a -s (S/../../(2|4)/01|L/../../6/01) -m reports112@freehost.com.ua -M diminishing'

      tags: ssd3
      
                    
    - name: Delete default smart line
      lineinfile: dest=/etc/smartd.conf
                  regexp='^DEVICESCAN -d'
                  state=absent

      
    - name: Restart smart
      service:
         name: smartd
         state: restarted
               
    - name: Check mdadm exist
      stat:
       path: /etc/mdadm/mdadm.conf
      register: stat_result

    - name: Change mdadm conf
      lineinfile: dest=/etc/mdadm/mdadm.conf backrefs=yes regexp='^MAILADDR' line='MAILADDR reports112@freehost.com.ua'
      when: stat_result.stat.exists
      
    - name: '/etc/fstab: Set options for mount point "/" '
      lineinfile:
        path: /etc/fstab
        backup: yes
        backrefs: yes
        regexp: '^(\S+\s+/\s+\S+\s+)(?!(?:\S*,)?discard(?:,\S*)?\s+)(\S+)(\s+.+)$'
        line: '\1discard,noatime,commit=120,\2\3'
      tags: ssd